板块设计,可以当作用户使用指南

** 网站镜像
国内一个 国外一个
访问速度,根据ip访问最近的镜像
备份一个出了问题,访问另一个
** 注册
*** 游客权限
** 登录
*** 使用github登录
登录的时候,可以创建一个新的帐号
邮箱 用户名 昵称
*** 使用微信登录
*** 使用手机号登录
** 发帖
*** 发帖权限
*** 图片
上传到网站的图片,要压缩一下
图片打水印 论坛地址
论坛上传图片,返回图片连接
直接是markdown的格式
支持批量操作
图片外联,可以限制,只能cnode域名访问吗?或者限制外联的调用次数
避免被当作图床使用

** 回复
*** 匿名回复
只是其他人看不到,论坛后台还是可以看到真实的用户信息
用于责任追究
*** 点赞
** 招聘
** 收藏
收藏用于保存有价值的回复消息,可以添加备注
是否提供修改功能?
一些高级会员可以提供
免费的会员,只能收藏,不能备注,修改

** 私信
** RSS
*** 订阅人
*** 订阅主题
*** 订阅帖子
订阅这个帖子后续的回复更新

** 个人中心
头像
主页
** 消息
** 管理人员
使用不同颜色来区分,管理 游客 注册会员
有问题@管理人员
20180320_154903.png
回复中默认隐藏点赞,只有鼠标移动到回复箭头处,才显示点赞按钮

微信公众号文章中设置的,是显示这个点赞的小手的
可以只显示那个回复的箭头,当鼠标停留在回复区域时,当条回复,显示所有的回复类型

回复 点赞 分享 订阅 匿名回复 收藏
分享,将这个文章分享到,社交网站上
可以定制自己常用的,之后的隐藏在"更多"中,点击可以选择



会员执行相关操作,帐号不满足相关权限.提示信息,这个需要的积分等级,开通指导,开通后,同时获得的权限清单

绑定自己的帐号key之外,可以分享到社区中
需要社区这边,抓取吗?
还是社交app中提供这样的调用接口
这个可以显示在人的动态中
类似于朋友圈功能
关系连在社区中

记录每个帖子上次浏览之后的位置,在标题后面,显示消息更新的数量
像微信群那样
可以选择忽略
默认是关闭的,rss当前帖子之后才会显示
这样可以降低服务器的压力

回复框中,可以选择表情
按照微信中的
选择一些常用的表情
可以保存自定义表情,那种微信斗图的?

论坛的人,达到一定级别,可以对论坛中违规的人,进行扣分
根据所处的位置,自动下拉候选,扣分的理由

标题
回复
帐号
这样全名监督,都个人都会有参与感
共同维护论坛的秩序

每一个主题贴都是一个markdown文件
那些不使用markdown语法,使用默认网页编辑的帖子,还是和正常一样
只是为那些高级用户提供一个接口,可以用narkdown文件来发布帖子
方便自己版控,及时更新,维护.
可以将回复中的内容整合到正文中
使用nodejs做一个工具
选择文件,打开 md文件 
预览
发布
最后生成的也是html文档,可以将对应主题的html文档作为发布形式吗?
在本地导出html,上传到论坛

cndoe的源码,学习的时候,注释直接在当前行后面添加.这样不会破坏原先代码的行数
使用差异文件查看时,也是显示在一行中
注释直接注释在代码中,可以及时跟随版本
注释也可以及时跟随代码的变化

写工具将markdown转换成cndoe支持的语法
这个应该有现成工具

发布到cnode中
这个环节用nodejs写个命令行工具,供第三方调用

每个项目开发的周期为一周,
要控制项目的大小,降低复杂度,在一个星期能完成
3个人,技能补充,人员备份,一些工作分工
奖金比例1135 按照贡献奖励100 300 500 完成后平台奖励100
培养团队人才
入门的人,简单的工作
代码的协作都放在github中,
开一个分支供这个项目开发团队用,每天构建,自动化构建,集成到最新版本中
及时处理冲突



可以将这个工具做到服务器上,上传markdown文件,可以在本地预览.预览之后,发布

本地预览,需要客户端上操作.

发表帖子或者回复 要有草稿功能

https://forums.debiancn.org/t/topic/1355
论坛机器人
这个机器人有什么功能
cnode也做一个机器人

https://cnodejs.org/topic/5aae829ff5dfc27d7ad98932
论坛中的连接自动转换成短网址
20180320_161118.png
短网址解析先用新浪的t.cn 之后不是复杂对性能要求不高的话,自己做

有积分奖励的帖子,用红色赏字,标识一下.
显示在标题前面,后面标识上赏的金额?

发帖类型中,选择类型
分享
 设置积分.达到这个积分后,帖子会被设置成公开
** 提问
  不强制悬赏 悬赏金额 着急或者需要好的答案,可以追加悬赏
** 悬赏
  设置悬赏金额
  其他人也想得到相关答案,也可以追加悬赏
  悬赏有效期
** 招聘
 招聘会自动按照时间天数来扣除.每天多少积分.每周 会有优惠
直到关闭招聘帖子
没有关闭,就认为是帖子还有效.
就可以投简历
** 测试
https://cnodejs.org/topic/5aae1cc8f5dfc27d7ad98909
公测帖子
