** 为什么用eggjs
*** 代码质量高
eggjs是阿里出品,由国内一线人员开发维护,总结实践经验抽象成框架,剥离阿里实际业务.
*** 中文沟通方便
国内开发者发起,中文语言沟通方便.
*** 文档齐全
*** 维护及时
github cnode论坛上有提问,egg成员及时耐心回复.

** 为什么用egg-cnode
*** MIT协议
mit协议开放,具体内容参见
mit-ruanyifeng.jpg

修改源码后可以闭源.方便一些商业版权的代码,以api的形式提供功能.

每一个修改过的文件不必须放置版权说明.

衍生软件的广告,可以使用源码的名字促销.

*** 实际上线运行
cnodejs.org论坛使用的这个,长时间运行,基本功能稳定.
*** 使用前沿量产技术栈
nodeclub由nodejs爱好者发起维护,朴大使用eggjs重构.使用的是实际开发中成熟前沿的技术和工具链.

** 为什么不在原项目做要fork新的
*** 侧重学习
使用egg-cnode为基础,我主要是为了学习nodejs开发.网上资料参差不齐,自己在学习上走了很多弯路,最后决定选择一个有实用价值,能长期存在的项目,先用起来,帮助别人用起来,理解需要修改或扩展功能相关部分的代码,恶补涉及到的知识点.目标驱动来学习

*** 学习论坛架构的各个方面
自己对论坛迷之执着.博客交互性不足,微信,qq,slack等及时通讯软件,信息组织归类缺失,平台监管严格,扩展定制性不足.

一个实际论坛的运行,不只是上线一个论坛,还有运维,运营,安全防护,用户交流反馈等等.安全性,稳定性,易用性,易维护性都需要很多工作.这些环节涉及到的技术,我会使用nodejs生态来实现.在实践中不断发现问题解决问题,不断改善优化.

使用egg-cnode,搭建,维护,运营一个交流使用egg-cnode的论坛,来贯穿涉及知识点的学习,开发满足论坛实际使用中产生的需求的插件.

*** 论坛后台自己可控
域名空间注册在国外,还可以摆脱国内的监管.

*** github高级权限
自己fork一个新的repo,可以有github上这个repo的所有权限,方便集成自动化测试,持续集成,以及对repo和team的管理.

自己的一些想法,能够有机会去尝试.说服别人的成本是很高的,认知不同去沟通的成本,其实这些精力已经可以将自己的想法实现,并在实践中得出了结论.

*** 组织形式
我只是这个项目的发起者,用文字,代码和行动来解释自己要做什么,怎么做.

有相同目标,认可价值观和做事方式的小伙伴可以加入进来,论坛组织形式会参考debian社区的运作方式.

*** fork形式方便回馈
fork形式很方便给原项目提pr.将自己的改进,建议回馈给上游,同时又能保留那些不被接受的功能特性和改进.

** 